insert into pets (id, name, description) values (1, 'Fox, blue', 'Alopex lagopus');
insert into pets (id, name, description) values (2, 'Pheasant, ring-necked', 'Phasianus colchicus');
insert into pets (id, name, description) values (3, 'Seal, harbor', 'Phoca vitulina');
insert into pets (id, name, description) values (4, 'Swallow (unidentified)', 'unavailable');
insert into pets (id, name, description) values (5, 'Moccasin, water', 'Agkistrodon piscivorus');
insert into pets (id, name, description) values (6, 'Ass, asiatic wild', 'Equus hemionus');
insert into pets (id, name, description) values (7, 'Red-tailed phascogale', 'Phascogale calura');
insert into pets (id, name, description) values (8, 'Tammar wallaby', 'Macropus eugenii');
insert into pets (id, name, description) values (9, 'Baboon, yellow', 'Papio cynocephalus');
insert into pets (id, name, description) values (10, 'Cow, scottish highland', 'Bos taurus');
insert into pets (id, name, description) values (11, 'Ring dove', 'Columba palumbus');
insert into pets (id, name, description) values (12, 'Black-tailed deer', 'Odocoileus hemionus');
insert into pets (id, name, description) values (13, 'Meerkat', 'Suricata suricatta');
insert into pets (id, name, description) values (14, 'Four-horned antelope', 'Tetracerus quadricornis');
insert into pets (id, name, description) values (15, 'Fowl, helmeted guinea', 'Numida meleagris');
insert into pets (id, name, description) values (16, 'Cat, tiger', 'Dasyurus maculatus');
insert into pets (id, name, description) values (17, 'African clawless otter', 'Aonyx capensis');
insert into pets (id, name, description) values (18, 'Fox, grey', 'Vulpes cinereoargenteus');
insert into pets (id, name, description) values (19, 'Collared lizard', 'Crotaphytus collaris');
insert into pets (id, name, description) values (20, 'Cardinal, red-capped', 'Paroaria gularis');
insert into pets (id, name, description) values (21, 'Dog, raccoon', 'Nyctereutes procyonoides');
insert into pets (id, name, description) values (22, 'Flightless cormorant', 'Nannopterum harrisi');
insert into pets (id, name, description) values (23, 'Water monitor', 'Varanus salvator');
insert into pets (id, name, description) values (24, 'Rabbit, eastern cottontail', 'Sylvilagus floridanus');
insert into pets (id, name, description) values (25, 'Wolf, common', 'Canis lupus');
insert into pets (id, name, description) values (26, 'Wolf spider', 'Lycosa godeffroyi');
insert into pets (id, name, description) values (27, 'Spider, wolf', 'Lycosa godeffroyi');
insert into pets (id, name, description) values (28, 'White-lipped peccary', 'Tayassu pecari');
insert into pets (id, name, description) values (29, 'Dog, bush', 'Speothos vanaticus');
insert into pets (id, name, description) values (30, 'Civet, small-toothed palm', 'Arctogalidia trivirgata');
insert into pets (id, name, description) values (31, 'Ring-tailed gecko', 'Cyrtodactylus louisiadensis');
insert into pets (id, name, description) values (32, 'Long-tailed jaeger', 'Stercorarius longicausus');
insert into pets (id, name, description) values (33, 'Two-toed sloth', 'Choloepus hoffmani');
insert into pets (id, name, description) values (34, 'Mongoose, yellow', 'Cynictis penicillata');
insert into pets (id, name, description) values (35, 'Corella, long-billed', 'Cacatua tenuirostris');
insert into pets (id, name, description) values (36, 'Barbet, levaillant''s', 'Trachyphonus vaillantii');
insert into pets (id, name, description) values (37, 'Sandhill crane', 'Grus canadensis');
insert into pets (id, name, description) values (38, 'Falcon, peregrine', 'Falco peregrinus');
insert into pets (id, name, description) values (39, 'Ringtail', 'Bassariscus astutus');
insert into pets (id, name, description) values (40, 'Crane, black-crowned', 'Balearica pavonina');
insert into pets (id, name, description) values (41, 'Cormorant, large', 'Phalacrocorax carbo');
insert into pets (id, name, description) values (42, 'Owl, snowy', 'Nyctea scandiaca');
insert into pets (id, name, description) values (43, 'Blacksmith plover', 'Vanellus armatus');
insert into pets (id, name, description) values (44, 'Red-headed woodpecker', 'Melanerpes erythrocephalus');
insert into pets (id, name, description) values (45, 'Porcupine, prehensile-tailed', 'Coendou prehensilis');
insert into pets (id, name, description) values (46, 'Boar, wild', 'Sus scrofa');
insert into pets (id, name, description) values (47, 'Gambel''s quail', 'Callipepla gambelii');
insert into pets (id, name, description) values (48, 'Hoary marmot', 'Marmota caligata');
insert into pets (id, name, description) values (49, 'Bustard, kori', 'Choriotis kori');
insert into pets (id, name, description) values (50, 'Eastern dwarf mongoose', 'Helogale undulata');
insert into pets (id, name, description) values (51, 'Royal tern', 'Thalasseus maximus');
insert into pets (id, name, description) values (52, 'Beaver, european', 'Castor fiber');
insert into pets (id, name, description) values (53, 'Rat, arboral spiny', 'Echimys chrysurus');
insert into pets (id, name, description) values (54, 'Lizard, blue-tongued', 'Tiliqua scincoides');
insert into pets (id, name, description) values (55, 'Sloth, two-toed tree', 'Choloepus hoffmani');
insert into pets (id, name, description) values (56, 'Southern boubou', 'Laniarius ferrugineus');
insert into pets (id, name, description) values (57, 'Huron', 'Galictis vittata');
insert into pets (id, name, description) values (58, 'Baboon, chacma', 'Papio ursinus');
insert into pets (id, name, description) values (59, 'Red-legged pademelon', 'Thylogale stigmatica');
insert into pets (id, name, description) values (60, 'Lion, south american sea', 'Otaria flavescens');
insert into pets (id, name, description) values (61, 'Eastern white pelican', 'Pelecans onocratalus');
insert into pets (id, name, description) values (62, 'Squirrel, nelson ground', 'Ammospermophilus nelsoni');
insert into pets (id, name, description) values (63, 'Secretary bird', 'Sagittarius serpentarius');
insert into pets (id, name, description) values (64, 'Cape cobra', 'Naja nivea');
insert into pets (id, name, description) values (65, 'Blue and gold macaw', 'Ara ararauna');
insert into pets (id, name, description) values (66, 'Rat, white-faced tree', 'Echimys chrysurus');
insert into pets (id, name, description) values (67, 'Tortoise, desert', 'Gopherus agassizii');
insert into pets (id, name, description) values (68, 'Silver-backed jackal', 'Canis mesomelas');
insert into pets (id, name, description) values (69, 'Cape wild cat', 'Felis libyca');
insert into pets (id, name, description) values (70, 'Dusky gull', 'Larus fuliginosus');
insert into pets (id, name, description) values (71, 'Bohor reedbuck', 'Redunca redunca');
insert into pets (id, name, description) values (72, 'Screamer, southern', 'Chauna torquata');
insert into pets (id, name, description) values (73, 'Great egret', 'Casmerodius albus');
insert into pets (id, name, description) values (74, 'Common seal', 'Phoca vitulina');
insert into pets (id, name, description) values (75, 'Macaw, green-winged', 'Ara chloroptera');
insert into pets (id, name, description) values (76, 'Blue wildebeest', 'Connochaetus taurinus');
insert into pets (id, name, description) values (77, 'Peacock, blue', 'Pavo cristatus');
insert into pets (id, name, description) values (78, 'Whale, southern right', 'Eubalaena australis');
insert into pets (id, name, description) values (79, 'Currasow (unidentified)', 'Crax sp.');
insert into pets (id, name, description) values (80, 'Fringe-eared oryx', 'Oryx gazella callotis');
insert into pets (id, name, description) values (81, 'Fox, grey', 'Vulpes cinereoargenteus');
insert into pets (id, name, description) values (82, 'Rattlesnake, eastern diamondback', 'Crotalus adamanteus');
insert into pets (id, name, description) values (83, 'Turtle (unidentified)', 'unavailable');
insert into pets (id, name, description) values (84, 'Wallaby, red-necked', 'Macropus rufogriseus');
insert into pets (id, name, description) values (85, 'Blue catfish', 'Ictalurus furcatus');
insert into pets (id, name, description) values (86, 'Common boubou shrike', 'Laniarius ferrugineus');
insert into pets (id, name, description) values (87, 'Tree porcupine', 'Coendou prehensilis');
insert into pets (id, name, description) values (88, 'White-throated kingfisher', 'Halcyon smyrnesis');
insert into pets (id, name, description) values (89, 'White-bellied sea eagle', 'Haliaetus leucogaster');
insert into pets (id, name, description) values (90, 'Crane, wattled', 'Bugeranus caruncalatus');
insert into pets (id, name, description) values (91, 'Grizzly bear', 'Ursus arctos');
insert into pets (id, name, description) values (92, 'Insect, stick', 'Leprocaulinus vipera');
insert into pets (id, name, description) values (93, 'Common langur', 'Semnopithecus entellus');
insert into pets (id, name, description) values (94, 'Pied crow', 'Corvus albus');
insert into pets (id, name, description) values (95, 'Mongoose, banded', 'Mungos mungo');
insert into pets (id, name, description) values (96, 'Reindeer', 'Rangifer tarandus');
insert into pets (id, name, description) values (97, 'Crane, sandhill', 'Grus canadensis');
insert into pets (id, name, description) values (98, 'Coqui partridge', 'Francolinus coqui');
insert into pets (id, name, description) values (99, 'Cape clawless otter', 'Aonyx capensis');
insert into pets (id, name, description) values (100, 'Southern black-backed gull', 'Larus dominicanus');
