swagger: "2.0"
info:
  version: "1.0.0"
  title: Pet API
host: localhost:8080
paths:
  /pets:
    get:
      summary: Retrieve all pets
      responses:
        '200':
          description: A list of pets
          schema:
            type: array
            items:
              $ref: "#/definitions/Pet"
    post:
      summary: Create a new pet
      parameters:
        - name: pet
          in: body
          description: The pet object
          required: true
          schema:
            $ref: "#/definitions/Pet"
      responses:
        '200':
          description: OK
  /pets/search:
    get:
      summary: Search pets
      parameters:
        - name: query
          in: query
          description: The search query
          required: true
          type: string
      responses:
        '200':
          description: A list of matching pets
          schema:
            type: array
            items:
              $ref: "#/definitions/Pet"
  /pets/{id}:
    get:
      summary: Get a pet by ID
      parameters:
        - name: id
          in: path
          description: The ID of the pet
          required: true
          type: integer
          format: int64
      responses:
        '200':
          description: OK
          schema:
            $ref: "#/definitions/Pet"
    put:
      summary: Update a pet
      parameters:
        - name: id
          in: path
          description: The ID of the pet
          required: true
          type: integer
          format: int64
        - name: pet
          in: body
          description: The updated pet object
          required: true
          schema:
            $ref: "#/definitions/Pet"
      responses:
        '200':
          description: OK
    delete:
      summary: Delete a pet
      parameters:
        - name: id
          in: path
          description: The ID of the pet
          required: true
          type: integer
          format: int64
      responses:
        '200':
          description: OK
definitions:
  Pet:
    type: object
    properties:
      id:
        type: integer
        format: int64
      name:
        type: string
      description:
        type: string
